# Use a base image with the Java runtime
FROM openjdk:14-alpine

# Set the working directory
WORKDIR /app

# Copy the build.sbt file to the working directory
COPY build.sbt /app

# Copy the JAR file to the working directory
COPY target/scala-2.13/LogisticDeliverSimulator.jar /app

# Expose port 7500
EXPOSE 7500

# Start the server
CMD ["java", "-jar", "LogisticDeliverSimulator.jar"]
