


# Prometheus configuration

global:
  scrape_interval:     15s 
  evaluation_interval: 15s
  

# A scrape configuration containing exactly one endpoint to scrape:


scrape_configs:

  - job_name: 'prometheus'

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mongodb'
    scrape_interval: 30s
    scrape_timeout: 30s
  
    static_configs:
         - targets: ['mongo_exporter:9001']

  - job_name: 'kafka'
    static_configs:
         - targets: ['kafka:7071']




  
