
- module: docker
  enabled: true
    hosts: ["unix:///var/run/docker.sock"]
    period: 1m
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      #- image
      - memory
      - network


output.elasticsearch:
  hosts: ["http://localhost:9200"] ## Monitoring cluster

setup.dashboards:
  enabled: true
  
setup.kibana:   
host: ["http://localhost:5601"]
 

monitoring:
  enabled: true


 

  
